services:
"  - type: web"
"    name: smart-city"
"    env: python"
"    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
"    startCommand: gunicorn smart_city.wsgi"
"    envVars:"
"      - key: DJANGO_SECRET_KEY"
"        generateValue: true"
"      - key: DJANGO_DEBUG"
"        value: \"False\""
